name: node-nativelib

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test-nodejs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install ffi
        run: npm i ffi
        if: always()
      - name: Install ffi-rs
        run: npm i ffi-rs
        if: always()
      - name: Install ffi-napi
        run: npm i ffi-napi
        if: always()
      - name: Install sffi
        run: npm i sbffi
        if: always()
      - name: Test ffi
        run: node index.js


  test-ruby:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
      - run: ruby index.rb
        if: always()


  test-python3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run
        run: python index.py
        if: always()
